#!/bin/bash

if [ `ls results_${1}_${2}-${3}_random/ | wc -l` -gt 450 ]; then
  python filter.py --dff --ckt ${1}_${2}-${3}_random/bench/pyTrojan_${1}.bench-ckt.bench results_${1}_${2}-${3}_random/*.bench results_${1}_${2}-${3}_random/*.bench_ff
  tar -cf results_${1}_${2}-${3}.random.dff.filtered.tar results_${1}_${2}-${3}_random/*_filtered
  pigz results_${1}_${2}-${3}.random.dff.filtered.tar
  rm results_${1}_${2}-${3}/*_filtered
fi
