#!/bin/bash
# Copyright (c) 2016 Joseph Lenox
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE. 


mkdir -p ${1}_${2}-${3}/part
mkdir -p ${1}_${2}-${3}/bench
mkdir -p ${1}_${2}-${3}/input

python test.py --fullcapture --noinput --nopart --outdir ${1}_${2}-${3} --partitions partitioned/pyTrojan_${1}.bench_partitions.pickle -tc i85/${2}.bench --fullcapture --noinput --nopart partitioned/pyTrojan_${1}.bench-ckt.bench
cd ${1}_${2}-${3}/bench
for i in pyTrojan_pyTrojan_${1}.bench-ckt.bench_*-badckt.bench; do newname=$(echo $i | awk -F. '{ print $1"."$3"."$4 }' | cut -b 10- ); mv $i $newname; done
cd ../..
cp partitioned/pyTrojan_${1}.bench_inputs.pickle ${1}_${2}-${3}/input
cp partitioned/pyTrojan_${1}.bench-ckt.bench ${1}_${2}-${3}/bench
cp partitioned/pyTrojan_${1}.bench_partitions.pickle ${1}_${2}-${3}/part
