#!/bin/bash

mkdir -p ${1}_${2}-${3}/part bench
mkdir -p ${1}_${2}-${3}/input
python test.py -tc i85/${2}.bench --noinput --nopart partitioned/pyTrojan_${1}.bench-ckt.bench
cd bench 
for i in pyTrojan_pyTrojan_${1}.bench-ckt.bench_*-badckt.bench; do newname=$(echo $i | awk -F. '{ print $1"."$3"."$4 }' | cut -b 10- ); mv $i $newname; done
cd ..
mv *.pickle bench ${1}_${2}-${3}
cp partitioned/pyTrojan_s1196.bench_inputs.pickle ${1}_${2}-${3}/input
cp partitioned/pyTrojan_s1196.bench-ckt.bench ${1}_${2}-${3}/bench
cp partitioned/pyTrojan_s1196.bench_partitions.pickle ${1}_${2}-${3}/part
