#!/bin/bash
start=$1
end=$2
ckt=$3
shift
shift
shift
for k in $ckt; do 
  for j in $*; do
    for i in $(seq $start $end); do 
      ./rebuild ${k} ${j} ${i};
      ./run_rebuild ${k} ${j} ${i}; 
      ./filter ${k} $j ${i}; 
      ./filter-dff ${k} $j $i; 
      tar -czf results_${k}_${j}-${i}.all.tar.gz results_${k}_${j}-${i}
    done; 
  done; 
done
